In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('cian.csv')
df = df.set_index('Unnamed: 0')
df.head(10)

ID  объявления Количество комнат       Тип  \
Unnamed: 0                                               
0                271271157                 4  Квартира   
1                271634126                 4  Квартира   
2                271173086   4, Оба варианта  Квартира   
3                272197456   4, Оба варианта  Квартира   
4                273614615                 2  Квартира   
5                274837728                 3  Квартира   
6                273643908   5, Оба варианта  Квартира   
7                274475342                 3  Квартира   
8                273973191                 3  Квартира   
9                272900409                 4  Квартира   

                                   Метро                                Адрес  \
Unnamed: 0                                                                      
0           м. Смоленская (9 мин пешком)        Москва, улица Новый Арбат, 27   
1           м. Смоленская (8 мин пешком)        Москва, улица Новый Арбат, 27   
2           м. Смоленская (7 мин пешком)        Москва, улица Новый Арбат, 27   
3           м. Смоленская (3 мин пешком)     Москва, переулок Плотников, 21С1   
4            м. Арбатская (7 мин пешком)        Москва, улица Новый Арбат, 15   
5           м. Смоленская (5 мин пешком)  Москва, 1-й Смоленский переулок, 21   
6            м. Арбатская (4 мин пешком)        Москва, переулок Романов, 3С1   
7           м. Смоленская (3 мин пешком)            Москва, улица Арбат, 43С3   
8           м. Смоленская (9 мин пешком)      Москва, Новинский бульвар, 18С1   
9           м. Арбатская (10 мин пешком)          Москва, улица Арбат, 30/3С1   

                 Площадь, м2                        Дом   Парковка  \
Unnamed: 0                                                           
0                 200.0/20.0           5/16, Монолитный  подземная   
1            198.0/95.0/18.0  5/16, Монолитно-кирпичный  подземная   
2            200.0/116.0/4.0                       5/16  подземная   
3            170.0/95.0/17.0                        5/6  подземная   
4              58.0/38.0/5.0           12/26, Панельный        NaN   
5                       92.0                        3/7        NaN   
6           213.0/140.0/20.0                        4/5   наземная   
7              98.0/63.0/9.0            2/4, Монолитный  подземная   
8            120.0/95.0/10.0           5/10, Сталинский   открытая   
9             90.0/66.0/10.0            2/7, Сталинский   открытая   

                                                         Цена  \
Unnamed: 0                                                      
0           500000.0 руб./ За месяц, Залог - 500000 руб., ...   
1           500000.0 руб./ За месяц, Залог - 500000 руб., ...   
2           500000.0 руб./ За месяц, Залог - 500000 руб., ...   
3           400000.0 руб./ За месяц, Залог - 400000 руб., ...   
4           225000.0 руб./ За месяц, Залог - 225000 руб., ...   
5           470000.0 руб./ За месяц, Залог - 470000 руб., ...   
6           350000.0 руб./ За месяц, Залог - 350000 руб., ...   
7           250000.0 руб./ За месяц, Залог - 250000 руб., ...   
8           130000.0 руб./ За месяц, Залог - 130000 руб., ...   
9           210000.0 руб./ За месяц, Залог - 210000 руб., ...   

                              Телефоны  ...             Окна  \
Unnamed: 0                              ...                    
0                         +79166369231  ...              NaN   
1                         +79850608590  ...  На улицу и двор   
2           +79672086536, +79099269384  ...  На улицу и двор   
3           +79660342340, +79099269384  ...  На улицу и двор   
4                         +79852432860  ...  На улицу и двор   
5                         +79684728732  ...              NaN   
6           +79175135482, +79099269384  ...  На улицу и двор   
7                         +79152004882  ...          Во двор   
8                         +79153429055  ...         На улицу   
9               

In [3]:
df['Телефоны'].head(10)

Unnamed: 0
0                  +79166369231
1                  +79850608590
2    +79672086536, +79099269384
3    +79660342340, +79099269384
4                  +79852432860
5                  +79684728732
6    +79175135482, +79099269384
7                  +79152004882
8                  +79153429055
9                  +79850610614
Name: Телефоны, dtype: object

In [4]:
df.columns

Index(['ID  объявления', 'Количество комнат', 'Тип', 'Метро', 'Адрес',
       'Площадь, м2', 'Дом', 'Парковка', 'Цена', 'Телефоны', 'Описание',
       'Ремонт', 'Площадь комнат, м2', 'Балкон', 'Окна', 'Санузел',
       'Можно с детьми/животными', 'Дополнительно', 'Название ЖК',
       'Серия дома', 'Высота потолков, м', 'Лифт', 'Мусоропровод',
       'Ссылка на объявление'],
      dtype='object')

In [5]:
df.shape

(23368, 24)

In [6]:
df['ID  объявления'].nunique()

23368

In [7]:
# уникальные значения в id 
df[df.duplicated(keep=False) == True]

Empty DataFrame
Columns: [ID  объявления, Количество комнат, Тип, Метро, Адрес, Площадь, м2, Дом, Парковка, Цена, Телефоны, Описание, Ремонт, Площадь комнат, м2, Балкон, Окна, Санузел, Можно с детьми/животными, Дополнительно, Название ЖК, Серия дома, Высота потолков, м, Лифт, Мусоропровод, Ссылка на объявление]
Index: []

[0 rows x 24 columns]

In [8]:
df[df.duplicated(subset=['ID  объявления']) == True]

Empty DataFrame
Columns: [ID  объявления, Количество комнат, Тип, Метро, Адрес, Площадь, м2, Дом, Парковка, Цена, Телефоны, Описание, Ремонт, Площадь комнат, м2, Балкон, Окна, Санузел, Можно с детьми/животными, Дополнительно, Название ЖК, Серия дома, Высота потолков, м, Лифт, Мусоропровод, Ссылка на объявление]
Index: []

[0 rows x 24 columns]

In [9]:
df.dtypes

ID  объявления                int64
Количество комнат            object
Тип                          object
Метро                        object
Адрес                        object
Площадь, м2                  object
Дом                          object
Парковка                     object
Цена                         object
Телефоны                     object
Описание                     object
Ремонт                       object
Площадь комнат, м2           object
Балкон                       object
Окна                         object
Санузел                      object
Можно с детьми/животными     object
Дополнительно                object
Название ЖК                  object
Серия дома                   object
Высота потолков, м          float64
Лифт                         object
Мусоропровод                 object
Ссылка на объявление         object
dtype: object

In [10]:
df['Количество комнат'].tail(10)

Unnamed: 0
23358                   1
23359    3, Изолированная
23360                   1
23361                   1
23362                 NaN
23363                 NaN
23364                   1
23365     2, Оба варианта
23366                   2
23367     2, Оба варианта
Name: Количество комнат, dtype: object

In [11]:
df['Количество комнат'].unique()
# есть nan значения и Nan - их надо заменить

array(['4', '4, Оба варианта', '2', '3', '5, Оба варианта',
       '3, Изолированная', '5', '5, Изолированная', '2, Оба варианта',
       '3, Оба варианта', '6', '1', '4, Изолированная', '6, Оба варианта',
       '2, Изолированная', nan, '2, Смежная', '4, Смежная', '3, Смежная',
       '6, Изолированная', '1, Изолированная', '1, Оба варианта',
       '5, Смежная', '6, Смежная', '1, Смежная'], dtype=object)

In [12]:
df['Лифт'].unique()

array(['Пасс (4), Груз (1)', 'Пасс (1), Груз (1)', 'Пасс (1)', nan,
       'Пасс (3)', 'Пасс (4)', 'Пасс (2), Груз (1)', 'Пасс (2)',
       'Пасс (2), Груз (2)', 'Пасс (3), Груз (3)', 'Груз (4)',
       'Пасс (3), Груз (1)', 'Груз (1)', 'Пасс (1), Груз (2)', 'Груз (2)',
       'Пасс (3), Груз (2)', 'Пасс (4), Груз (4)', 'Пасс (2), Груз (3)',
       'Пасс (4), Груз (2)', 'Груз (3)', 'Пасс (1), Груз (3)',
       'Пасс (4), Груз (3)', 'Пасс (5), Груз (1)', 'Пасс (1), Груз (12)',
       'Пасс (60)', 'Пасс (6)', 'Пасс (8), Груз (8)', 'Пасс (7)',
       'Пасс (1), Груз (4)', 'Пасс (50)', 'Пасс (5), Груз (3)',
       'Пасс (2), Груз (4)', 'Груз (6)', 'Груз (8)', 'Пасс (5)'],
      dtype=object)

In [13]:
df.dtypes

ID  объявления                int64
Количество комнат            object
Тип                          object
Метро                        object
Адрес                        object
Площадь, м2                  object
Дом                          object
Парковка                     object
Цена                         object
Телефоны                     object
Описание                     object
Ремонт                       object
Площадь комнат, м2           object
Балкон                       object
Окна                         object
Санузел                      object
Можно с детьми/животными     object
Дополнительно                object
Название ЖК                  object
Серия дома                   object
Высота потолков, м          float64
Лифт                         object
Мусоропровод                 object
Ссылка на объявление         object
dtype: object

In [14]:
df['Ремонт'].unique()

array(['Дизайнерский', 'Евроремонт', 'Косметический', nan, 'Без ремонта'],
      dtype=object)

In [15]:
df['Мусоропровод'].unique()

array(['Да', 'Нет', nan], dtype=object)

In [16]:
df['Дополнительно'].unique()

array(['Мебель в комнатах, Мебель на кухне, Ванна, Душевая кабина, Стиральная машина, Кондиционер, Посудомоечная машина, Телевизор, Холодильник, Интернет, Телефон',
       'Мебель в комнатах, Мебель на кухне, Ванна, Душевая кабина, Стиральная машина, Кондиционер, Посудомоечная машина, Телевизор, Холодильник, Интернет',
       'Мебель в комнатах, Мебель на кухне, Ванна, Душевая кабина, Стиральная машина, Посудомоечная машина, Телевизор, Холодильник, Интернет',
       'Мебель в комнатах, Мебель на кухне, Ванна, Душевая кабина, Стиральная машина, Кондиционер, Посудомоечная машина, Телевизор, Холодильник',
       'Мебель в комнатах, Мебель на кухне, Ванна, Стиральная машина, Посудомоечная машина, Телевизор, Холодильник, Интернет, Телефон',
       'Мебель в комнатах, Мебель на кухне, Ванна, Душевая кабина, Стиральная машина, Кондиционер, Посудомоечная машина, Холодильник, Интернет',
       'Мебель на кухне, Ванна, Стиральная машина, Кондиционер, Посудомоечная машина, Телевизор, Холодильник,

In [17]:
len(df['Описание'].unique())

23078

In [18]:
df.dtypes

ID  объявления                int64
Количество комнат            object
Тип                          object
Метро                        object
Адрес                        object
Площадь, м2                  object
Дом                          object
Парковка                     object
Цена                         object
Телефоны                     object
Описание                     object
Ремонт                       object
Площадь комнат, м2           object
Балкон                       object
Окна                         object
Санузел                      object
Можно с детьми/животными     object
Дополнительно                object
Название ЖК                  object
Серия дома                   object
Высота потолков, м          float64
Лифт                         object
Мусоропровод                 object
Ссылка на объявление         object
dtype: object

In [19]:
df['Тип'].unique()

array(['Квартира'], dtype=object)

In [20]:
df['Площадь, м2'].unique()

array(['200.0/20.0', '198.0/95.0/18.0', '200.0/116.0/4.0', ..., '43.1',
       '52.5/10.0', '90.0/48.2/15.5'], dtype=object)

In [21]:
df['Дом'].unique()

array(['5/16, Монолитный', '5/16, Монолитно-кирпичный', '5/16', ...,
       '10/23, Монолитно-кирпичный', '12/23, Панельный', '12/25, Блочный'],
      dtype=object)

In [22]:
df['Парковка'].unique()

array(['подземная', nan, 'наземная', 'открытая', 'многоуровневая',
       'на крыше'], dtype=object)

In [23]:
df['Цена'].unique()

array(['500000.0 руб./ За месяц, Залог - 500000 руб., Коммунальные услуги включены, Срок аренды - Длительный, Предоплата 1 мес',
       '500000.0 руб./ За месяц, Залог - 500000 руб., Срок аренды - Длительный, Предоплата 1 мес',
       '400000.0 руб./ За месяц, Залог - 400000 руб., Срок аренды - Длительный, Предоплата 1 мес',
       ...,
       '48000.0 руб./ За месяц, Залог - 40000 руб., Коммунальные услуги включены, Срок аренды - На несколько месяцев, Предоплата 1 мес',
       '39000.0 руб./ За месяц, Залог - 40000 руб., Коммунальные услуги включены, Срок аренды - На несколько месяцев, Предоплата 1 мес',
       '55000.0 руб./ За месяц, Залог - 50000 руб., Коммунальные услуги включены, Срок аренды - Длительный, Предоплата 2 мес'],
      dtype=object)

In [24]:
df['Телефоны'].unique()

array(['+79166369231', '+79850608590', '+79672086536, +79099269384', ...,
       '+79653825192', '+79660611965', '+79623641533'], dtype=object)

In [25]:
df['Площадь комнат, м2'].unique()

array([nan, '25 25 20 25', '14-42-20-19', ..., '22-16-30', '32+13,6-18,7',
       '26,2+15,5-22,0'], dtype=object)

In [26]:
df['Балкон'].unique()

array([nan, 'Балкон (1)', 'Балкон (3)', 'Лоджия (1)',
       'Балкон (2), Лоджия (3)', 'Балкон (1), Лоджия (1)', 'Балкон (2)',
       'Лоджия (2)', 'Балкон (3), Лоджия (3)', 'Балкон (3), Лоджия (1)',
       'Лоджия (3)', 'Балкон (1), Лоджия (2)', 'Балкон (2), Лоджия (1)',
       'Балкон (2), Лоджия (2)', 'Балкон (1), Лоджия (3)', 'Балкон (4)',
       'Лоджия (4)', 'Балкон (4), Лоджия (4)', 'Балкон (1), Лоджия (4)'],
      dtype=object)

In [27]:
df['Окна'].unique()

array([nan, 'На улицу и двор', 'Во двор', 'На улицу'], dtype=object)

In [28]:
df['Санузел'].unique()

array([nan, 'Совмещенный (2), Раздельный (1)', 'Совмещенный (3)',
       'Совмещенный (2)', 'Совмещенный (1), Раздельный (1)',
       'Совмещенный (1)', 'Совмещенный (2), Раздельный (2)',
       'Раздельный (2)', 'Раздельный (1)', 'Раздельный (3)',
       'Совмещенный (4)', 'Совмещенный (3), Раздельный (1)',
       'Раздельный (4)', 'Совмещенный (1), Раздельный (2)',
       'Совмещенный (2), Раздельный (4)',
       'Совмещенный (1), Раздельный (3)',
       'Совмещенный (3), Раздельный (3)',
       'Совмещенный (4), Раздельный (2)',
       'Совмещенный (2), Раздельный (3)',
       'Совмещенный (4), Раздельный (1)',
       'Совмещенный (3), Раздельный (2)'], dtype=object)

In [29]:
df['Название ЖК'].unique()

array(['Новый Арбат, 2010', 'Новый Арбат', nan, ..., 'Лучи, 2019',
       'В Солнцево, 2013', 'В Солнцево'], dtype=object)